In [1]:
import warnings
warnings.filterwarnings(action = 'ignore')

import pandas as pd
import numpy as np

import os 

from tqdm.notebook import tqdm
tqdm.pandas()

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC

import time

In [2]:
test_list_filename = [file for file in os.listdir() if os.path.splitext(file)[-1] == '.xlsx'][0]
test_list_filename

'코딩 테스트 문제 리스트 정리.xlsx'

In [3]:
path_for_readme = '/Users/eunbinpark/workspace/git/Algorithm-Study/'
path_for_readme

'/Users/eunbinpark/workspace/git/Algorithm-Study/'

In [4]:
df = pd.read_excel(test_list_filename, header = 2).iloc[:-2, :-1]
df

,날짜,난이도,문제이름,링크
0,1 일차,Level 1,완주하지 못한 선수,https://programmers.co.kr/learn/courses/30/les...
1,2 일차,Level 1,가운데 글자 가져오기,https://programmers.co.kr/learn/courses/30/les...
2,3 일차,Level 1,수박수박수박수박수박수?,https://programmers.co.kr/learn/courses/30/les...
3,4 일차,Level 1,두 정수 사이의 합,https://programmers.co.kr/learn/courses/30/les...
4,5 일차,Level 1,서울에서 김서방 찾기,https://programmers.co.kr/learn/courses/30/les...
5,6 일차,Level 1,약수의 합,https://programmers.co.kr/learn/courses/30/les...
6,7 일차,Level 1,나누어 떨어지는 숫자 배열,https://programmers.co.kr/learn/courses/30/les...
7,8 일차,Level 1,같은 숫자는 싫어,https://programmers.co.kr/learn/courses/30/les...
8,9 일차,Level 1,문자열 내 p와 y의 개수,https://programmers.co.kr/learn/courses/30/les...
9,10 일차,Level 1,핸드폰 번호 가리기,https://programmers.co.kr/learn/courses/30/les...
10,11 일차,Level 1,체육복,https://programmers.co.kr/learn/courses/30/les...
11,12 일차,Level 1,직사각형 별찍기,https://programmers.co.kr/learn/courses/30/les...
12,13 일차,Level 1,시저 암호,https://programmers.co.kr/learn/courses/30/les...
13,14 일차,Level 1,소수 찾기,https://programmers.co.kr/learn/courses/30/les...
14,15 일차,Level 1,다트 게임,https://programmers.co.kr/learn/courses/30/les...
15,16 일차,Level 2,위장,https://programmers.co.kr/learn/courses/30/les...
16,17 일차,Level 2,가장 큰 수,https://programmers.co.kr/learn/courses/30/les...
17,18 일차,Level 2,타겟 넘버,https://programmers.co.kr/learn/courses/30/les...
18,19 일차,Level 2,주식가격,https://programmers.co.kr/learn/courses/30/les...
19,20 일차,Level 2,피보나치 수,https://programmers.co.kr/learn/courses/30/les...
20,21 일차,Level 2,소수 찾기,https://programmers.co.kr/learn/courses/30/les...
21,22 일차,Level 2,가장 큰 정사각형 찾기,https://programmers.co.kr/learn/courses/30/les...
22,23 일차,Level 2,점프와 순간 이동,https://programmers.co.kr/learn/courses/30/les...

In [5]:
def scraping_desc(url:str):    
    options = webdriver.ChromeOptions()
    options.add_argument('headless')
    
    web = '/Users/eunbinpark/workspace/chromedriver'
    
    driver = webdriver.Chrome(web, options=options)
    driver.get(url)
    
    desc_list = list()

    try:
        desc_list.append(driver.find_element_by_xpath('//*[@id="tour2"]/div/div/p[1]').text)
        desc_list.append(driver.find_element_by_xpath('//*[@id="tour2"]/div/div/p[2]').text)

    except:
        pass
    
    driver.close()
    
    return desc_list

In [6]:
descriptions_list = df['링크'].progress_map(scraping_desc).tolist()

HBox(children=(FloatProgress(value=0.0, max=23.0), HTML(value='')))

In [7]:
len(descriptions_list)

23

In [8]:
def is_exists_dir(dir_path, directory):
    directory = os.path.join(dir_path, directory)
    if not os.path.exists(directory):
        os.makedirs(directory)
        print('Create Dir' + directory)
            
    else:
        print('Already Exists' + directory)

        
def make_prob2md_file(day_count, prob_title, description, prob_url):
    md_format = f"""## Day {day_count}\n
### {prob_title}
{description}<br><br>
### URL
[{prob_title}]({prob_url})<br>"""
    
    return md_format

In [9]:
dir_names = ('Day ' + df['날짜'].map(lambda x: x.split()[0])).tolist()

for dir_name in dir_names:
    is_exists_dir(path_for_readme, dir_name)

Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 1
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 2
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 3
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 4
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 5
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 6
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 7
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 8
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 9
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 10
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 11
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 12
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 13
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 14
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 15
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 16
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 17
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 18
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 19
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 20
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 21
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 22
Create Dir/Users/eunbinpark/workspace/git/Algorithm-Study/Day 23

In [10]:
day_counts = df['날짜'].map(lambda x: x.split()[0]).tolist()
prob_titles = df['문제이름'].tolist()
# descriptions_list
urls = df['링크'].tolist()

In [11]:
final_df = pd.DataFrame(data = [dir_names, day_counts, prob_titles, descriptions_list, urls], index = ['dir_names', 'day_counts', 'prob_titles', 'desc_list', 'urls']).T
final_df['desc_list'] = final_df['desc_list'].map(lambda x: '<br>'.join(x))
final_df

,dir_names,day_counts,prob_titles,desc_list,urls
0,Day 1,1,완주하지 못한 선수,수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든...,https://programmers.co.kr/learn/courses/30/les...
1,Day 2,2,가운데 글자 가져오기,"단어 s의 가운데 글자를 반환하는 함수, solution을 만들어 보세요. 단어의 ...",https://programmers.co.kr/learn/courses/30/les...
2,Day 3,3,수박수박수박수박수박수?,"길이가 n이고, 수박수박수박수....와 같은 패턴을 유지하는 문자열을 리턴하는 함수...",https://programmers.co.kr/learn/courses/30/les...
3,Day 4,4,두 정수 사이의 합,"두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함...",https://programmers.co.kr/learn/courses/30/les...
4,Day 5,5,서울에서 김서방 찾기,"String형 배열 seoul의 element중 Kim의 위치 x를 찾아, 김서방은...",https://programmers.co.kr/learn/courses/30/les...
5,Day 6,6,약수의 합,"정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 ...",https://programmers.co.kr/learn/courses/30/les...
6,Day 7,7,나누어 떨어지는 숫자 배열,array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로...,https://programmers.co.kr/learn/courses/30/les...
7,Day 8,8,같은 숫자는 싫어,배열 arr가 주어집니다. 배열 arr의 각 원소는 숫자 0부터 9까지로 이루어져 ...,https://programmers.co.kr/learn/courses/30/les...
8,Day 9,9,문자열 내 p와 y의 개수,대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 ...,https://programmers.co.kr/learn/courses/30/les...
9,Day 10,10,핸드폰 번호 가리기,프로그래머스 모바일은 개인정보 보호를 위해 고지서를 보낼 때 고객들의 전화번호의 일...,https://programmers.co.kr/learn/courses/30/les...
10,Day 11,11,체육복,"점심시간에 도둑이 들어, 일부 학생이 체육복을 도난당했습니다. 다행히 여벌 체육복이...",https://programmers.co.kr/learn/courses/30/les...
11,Day 12,12,직사각형 별찍기,이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다.\n별(*) 문자를 ...,https://programmers.co.kr/learn/courses/30/les...
12,Day 13,13,시저 암호,어떤 문장의 각 알파벳을 일정한 거리만큼 밀어서 다른 알파벳으로 바꾸는 암호화 방식...,https://programmers.co.kr/learn/courses/30/les...
13,Day 14,14,소수 찾기,"1부터 입력받은 숫자 n 사이에 있는 소수의 개수를 반환하는 함수, solution...",https://programmers.co.kr/learn/courses/30/les...
14,Day 15,15,다트 게임,카카오톡에 뜬 네 번째 별! 심심할 땐? 카카오톡 게임별~<br>,https://programmers.co.kr/learn/courses/30/les...
15,Day 16,16,위장,스파이들은 매일 다른 옷을 조합하여 입어 자신을 위장합니다.<br>예를 들어 스파이...,https://programmers.co.kr/learn/courses/30/les...
16,Day 17,17,가장 큰 수,"0 또는 양의 정수가 주어졌을 때, 정수를 이어 붙여 만들 수 있는 가장 큰 수를 ...",https://programmers.co.kr/learn/courses/30/les...
17,Day 18,18,타겟 넘버,n개의 음이 아닌 정수가 있습니다. 이 수를 적절히 더하거나 빼서 타겟 넘버를 만들...,https://programmers.co.kr/learn/courses/30/les...
18,Day 19,19,주식가격,"초 단위로 기록된 주식가격이 담긴 배열 prices가 매개변수로 주어질 때, 가격이...",https://programmers.co.kr/learn/courses/30/les...
19,Day 20,20,피보나치 수,"피보나치 수는 F(0) = 0, F(1) = 1일 때, 1 이상의 n에 대하여 F(...",https://programmers.co.kr/learn/courses/30/les...
20,Day 21,21,소수 찾기,한자리 숫자가 적힌 종이 조각이 흩어져있습니다. 흩어진 종이 조각을 붙여 소수를 몇...,https://programmers.co.kr/learn/courses/30/les...
21,Day 22,22,가장 큰 정사각형 찾기,1와 0로 채워진 표(board)가 있습니다. 표 1칸은 1 x 1 의 정사각형으로...,https://programmers.co.kr/learn/courses/30/les...
22,Day 23,23,점프와 순간 이동,"OO 연구소는 한 번에 K 칸을 앞으로 점프하거나, (현재까지 온 거리) x 2 에...",https://programmers.co.kr/learn/courses/30/les...

In [12]:
for i in final_df.itertuples():
    dir_name = i[1]
    day_count = i[2]
    prob_title = i[3]
    description = i[4]
    url = i[5]
    
    with open(os.path.join(path_for_readme, dir_name, 'README.md'), 'w') as f:
        f.write(make_prob2md_file(day_count, prob_title, description, url))